name: utopia_queue_example
description: Example for Utopia Queue library
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf:
  utopia_queue:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
