name: utopia_queue
description: Light and easy to use queue library for Dart server projects
version: 0.3.0
repository: https://github.com/utopia-dart/utopia_queue

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  redis: ^4.0.0
  utopia_di: ^0.2.0
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
