name: utopia_queue
description: Light and fast queue library for Dart server projects
version: 0.0.1
repository: https://github.com/utopia-dart/utopia_queue

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  redis: ^4.0.0
  utopia_di: ^0.0.2
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
